### ISSUE TITLE
[Python] GML and CRL implementation

### ISSUE THREAD

**Issue by scmanjarrez** [IBM/libgroupsig#68]
Hi,
First of all, thanks for your work.

I want to know if is it possible to remove a member from the GML (or revoke from CRL) from the python wrapper. 
I've looked at the code, but only import/export functions are defined, lot of functions from [gml.c](https://github.com/IBM/libgroupsig/blob/master/src/groupsig/gml.c) and [crl.c](https://github.com/IBM/libgroupsig/blob/master/src/groupsig/crl.c) are missing. Also, is it possible to import a GML from disk? I saw that it's possible to pass GML as argument in join_mgr, however, it's never used.

Another doubt, is it possible to use grpkey-mgrkey the same as public-key cryptography? I mean, can I cipher the message with the grpkey, send it over the network and decrypt it using mgrkey?

P.S.: why [grpkey.py](https://github.com/IBM/libgroupsig/blob/master/src/wrappers/python/pygroupsig/grpkey.py) has `grpkey_to_string` commented out? I checked the [C](https://github.com/IBM/libgroupsig/blob/master/src/groupsig/grp_key.c) implementation but it's uncommented.

P.S2.: After some tests, I've seen that you decode the base64 string in mostly all `*_export` functions except gml_export, is there any particular reason for that?

Best regards,
S.

**Comment by jdv-ibm** [comment]
Hi, S.

Sorry for the late reply. I hope this still comes in time...

*Remove members from GMLs and CRLs* (in Python wrapper)

It is indeed not possible to remove entries (members) from the GMLs or CRLs, in the Python wrapper, although the C library does offer that possibility. It should not be hard to add it to Python, anyway. 

However, take into account that GMLs and CRLs are lists used by the underlying schemes to "keep track" of the users who have joined the group (this would be GMLs), and the users who have been revoked (the CRLs). So modifications to these lists should be left to the group signature scheme functionality (for the schemes that support it). Manually editing them could lead to incoherent behavior. What scheme are you interested in? I'd have to look, as I do not remember by hard, by I think none of the currently supported schemes in Python makes use of a CRL, for instance)

*Usage of grpkey-mgrkey as in public key crypto*

Encrypting messages with the group public key is not possible. Group signature schemes are designed only for signing, not for encryption. If you need an encryption scheme with recipient privacy, maybe [group encryption](https://link.springer.com/content/pdf/10.1007/978-3-540-76900-2_11.pdf) can be useful, although I am not familiar with that primitive nor its implementations (if there is any...)

*Why is grpkey_to_string commented out* (in Python wrapper)

The grpkey_to_string in most of the schemes, in the C library, return NULL. This is basically because I've had no time (nor the real need) to print keys of any type in human readable form yet. This is why the equivalent in the Python wrapper is commented out, because it would lead to placeholder functions in most cases. "Laziness" from my side, for sure. It should not be hard to add, however.

*Decoding base64 string in _export functions except gml_export*

Note that this is not an instruction that decodes a Base64 string into a (binary) string. It just removes all '\n' chars from the string. In the other places where I do the decode, this was necessary (if I remember correctly) to make the base64 encoding in Python consistent with the base64 encoding in other variants of the library (C, Java, NodeJS), where no '\n' chars are added between lines.

The fact that gml_export lacks that, is is probably because I have not heavily used (for higher-level applications) group signature schemes that rely on GMLs. Thus, GMLs missing that line may just be that I overlooked it. If you try to export a GML from Python and import from other wrapper and it does not work, that may very well be the reason...

PS: As you see, there is plenty of refinement and further work to be done. Feel free to make a pull request!
